# Site settings
title: Shazad Ali
email: shazadali09@hotmail.co.uk
description: > # this means to ignore newlines until "baseurl:"
  My personal website, blog and work.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shazad-ali.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  shazad-ali

permalink: /blog/:year/:month/:day/:title

# Build settings
markdown: kramdown
